### ISSUE TITLE
What the different TagTypeId's?

### ISSUE THREAD

**Issue by jbrinchmann** [EnergieID/cloogy#1]
Hi, 
Thank you for this very useful package! I was wondering whether you have any information about what the different TagTypeId values are. You state that 20001 correspond to current consumption but I did not find information about the others.

**Comment by JrtPec** [comment]
Hi, I have put the API docs used to write the code [here](https://github.com/EnergieID/cloogy/blob/master/iEnergy3%20API%20-%20VPS.pdf).

In the PDF you can find some examples that use 20001, so I think that's where I got it from. I don't have any more examples unfortunately.
